### ISSUE TITLE
პრობლემა make-ის გამოძახებისას

### ISSUE THREAD

**Issue by ltsil19** [freeuni-paradigms/assn-4-rss-news-search#1]
ტერმინალის აუთფუთი:

gcc rss-news-search.o -g  -m32 -Wall -std=gnu99 -Wno-unused-function -g  -lnsl -lrssnews -lcurl -Llinux -o rss-news-search
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../libnsl.so when searching for -lnsl
/usr/bin/ld: skipping incompatible /usr/lib/libnsl.so when searching for -lnsl
/usr/bin/ld: cannot find -lnsl
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../libnsl.so when searching for -lnsl
/usr/bin/ld: skipping incompatible /usr/lib/libnsl.so when searching for -lnsl
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: rss-news-search] Error 1

პრერეკვიზიტები valgrind და curl დაინსტალირებული მაქვს.
სისტემა Arch-ზეა დაფუძნებული.

**Comment by gkhelo** [comment]
gcc-multilibის დაყენება გჭირდება სავარაუდოდ. Arch linux არ მაქვს და ვერ ვტესატვ, მაგრამ წესით ასე უნდა იყოს: sudo pacman -S gcc-multilib

**Comment by ltsil19** [comment]
ეგეც დაინსტალირებულია, ყოველი შემთხვევისთვის თავიდან დავაინსტალე და არაფერი შეცვლილა.

sudo pacman -S gcc-multilib
warning: gcc-10.2.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) gcc-10.2.0-2

Total Installed Size:  147,32 MiB
Net Upgrade Size:        0,00 MiB

**Comment by gkhelo** [comment]
გასაგებია. აბა ესენი ცადე

sudo dpkg --add-architecture i386
sudo apt-get install libc6:i386

**Comment by ltsil19** [comment]
ეგ command-ები მგონი Arch-ზე არ მუშაობს

**Comment by gkhelo** [comment]
მეორე ასე გაუშვი: sudo pacman -S libc6:i386
და პირველი არ ეშვება? dpkg მგონი arch linux-ზეც უნდა იყოს

**Comment by ltsil19** [comment]
libc6:i386 ან რამე მსგავსი არ არის რეპოზიტორიებში და dpkg მხოლოდ Debian-ისთვისაა

**Comment by gkhelo** [comment]
sudo pacman -S multilib-devel
ესეც ცადე აბა. ზოგადად პრობლემა ისაა, რომ 32ბიტიანი ბიბლიოთეკის დაკომპილირებას ცდილობ 64ბიტიან სისტემაზე. მეც მქონდა მსგავსი პრობლემა და gcc-multilibის დაყენებამ უშველა. რო დასერჩო ბევრი ვარიანტია მსგავსი ბიბლიოთეკების და რომელიმე აუცილებლად იმუშავებს :)

**Comment by ltsil19** [comment]
მოკლედ უამრავი package დავაინსტალე და ღმერთმა იცის რომელმა იმუშავა, მაგრამ, ჩემი აზრით, libnsl და lib32-libnsl იყო საჭირო :დ

**Comment by iarigby** [comment]
აზრით რა, პირდაპირ წერდა

/usr/bin/ld: cannot find -lnsl

მე არ მქონდა დრო ამ დავალების არჩზე დასატესტად და ამის გამო ვეღარ ჩავამატე
ინსტრუქცია რომ არ გეწვალა.

ზოგადად მაგ ერორ მესიჯების ახსნა (მომავალში სასარგებლო იქნება)

/usr/bin/ld - ლინკერი

/usr/bin/ld: skipping incompatible
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../libnsl.so when searching
for -lnsl

რადგანაც კომპაილერს -m32 აქვს, 64 ბიტიანი ვერსია არ გამოიყენა. 32იანის
დაინსტალირება იყო საჭირო მარტო.

**Comment by shughla** [comment]
ზუსტად რა package უნდა დავაყენო?

**Comment by shughla** [comment]
lib32-libnsl-ს მერე warning-ებს მაინც აგდებს 
```
gcc rss-news-search.o -g  -m32 -Wall -std=gnu99 -Wno-unused-function -g  -lnsl -lrssnews -lcurl -Llinux -o rss-news-search
/usr/bin/ld: linux/librssnews.a(url.o): warning: relocation in read-only section `.rodata'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE

```

**Comment by iarigby** [comment]
რამე პრობლემა იქმნება მაგ ვორნინგების გამო?

**Comment by shughla** [comment]
ჯერ არ ვიცი ;დ
