### ISSUE TITLE
ასერტი მაგალითის გაშვებისას

### ISSUE THREAD

**Issue by mashokh** [freeuni-paradigms/assn-4-rss-news-search#10]
./rss-news-search-linux -ს რომ ვუშვებ rss-news-search-linux: rss-news-search.c:116: Welcome: Assertion `infile != ((void *)0)' failed.
Aborted (core dumped)
ამ ასერტს მიგდებს და რატო? ვერ გავასწორე

**Comment by giorgi43** [comment]
ჩემთანაც იგივეს აკეთებს. თუ არგუმენტად გადავცემ რომელიმე ფაილს მაგალითად `./rss-news-search-linux data/rss-feeds-tiny.txt` ირთვება ჩვეულებრივ მაგრამ მაგალითად `data/rss-feeds-large.txt` ამაზე ასერტს აგდებს ისევ. ანუ ზოგ ფაილზე აკეთებს ზოგზე არა. ასევე რომელზეც არ აგდებს ასერტს და თუ სიტყვას შევიყვან მოსაძებნად ყველაფერზე წერს რო ვერცერთ არტიკლში მოიძებნაო, ბევრი სიტყვა ვცადე და მგონი თვითონ ამ sample-ს პრობლემაა, არ მუშაობს სწორად..

**Comment by LevanSamadashvili** [comment]
./rss-news-search მუშაობს ჩვეულებრივად ჩემთან, ლინუქსი როაწერია არა ვაბშე ;დდ

**Comment by d-chechelashvili** [comment]
წინასწარ დაკომპილირებულ ვერსიაა ეგ დავალების კოდის და ზუსტად რა პარამეტრებს ითხოვს რომ იმუშაოს არც ჩვენ ვიცით, იმიტომ რომ კოდი არ გვაქვს. ასე რომ, სამწუხაროდ არ გვაქვს ამ დავალებაში დემო ვერსია.
