### ISSUE TITLE
lcurl issue

### ISSUE THREAD

**Issue by ZukaChilachava** [freeuni-paradigms/assn-4-rss-news-search#11]
გამარჯობა, 
make ს რომ ვაკეთებ მეოთხე ესაინმენთის დირექტორიაში ასეთ რაღაცას მიგდებს:
gcc rss-news-search.o -g  -m32 -Wall -std=gnu99 -Wno-unused-function -g  -lnsl -lrssnews -lcurl -Llinux -o rss-news-search
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libcurl.so when searching for -lcurl
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libcurl.a when searching for -lcurl
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: rss-news-search] Error 1 

დახურულ issue ებს რომ გადავხედე ეს იყო სოლუშენი, მაგრამ მე რო ვუშვებ ასეთი რაღაც ხდება 
sudo dpkg --add-architecture i386
sudo apt-get install libcurl4:i386
sudo apt-get install libcurl4-gnutls-dev:i386

Do you want to continue? [Y/n] y
Err:1 http://ge.archive.ubuntu.com/ubuntu focal-updates/main amd64 zlib1g amd64 1:1.2.11.dfsg-2ubuntu1.1
  404  Not Found [IP: 217.147.227.66 80]
Err:2 http://ge.archive.ubuntu.com/ubuntu focal-updates/main i386 zlib1g i386 1:1.2.11.dfsg-2ubuntu1.1
  404  Not Found [IP: 217.147.227.66 80]
Err:3 http://ge.archive.ubuntu.com/ubuntu focal-updates/main i386 libldap-2.4-2 i386 2.4.49+dfsg-2ubuntu1.3
  404  Not Found [IP: 217.147.227.66 80]
E: Failed to fetch http://ge.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g_1.2.11.dfsg-2ubuntu1.1_amd64.deb  404  Not Found [IP: 217.147.227.66 80]
E: Failed to fetch http://ge.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g_1.2.11.dfsg-2ubuntu1.1_i386.deb  404  Not Found [IP: 217.147.227.66 80]
E: Failed to fetch http://ge.archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.49+dfsg-2ubuntu1.3_i386.deb  404  Not Found [IP: 217.147.227.66 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by glekveishvili** [comment]
32 ბიტიანი ვერსია უნდა დააყენო curl-ის: libcurl4-gnutls-dev:i386
ინსტრუქციებსი არის ახსნილი: https://github.com/freeuni-paradigms/assn-4-rss-news-search
