### ISSUE TITLE
FetchURL NULL-ს აბრუნებს

### ISSUE THREAD

**Issue by nniko18** [freeuni-paradigms/assn-4-rss-news-search#13]
./rss-news-search-ის გაშვებისას ამას აგდებს. printf-ებით რაც ვნახე, მგონი FetchURL-ის if (res != CURLE_OK) ბლოკში შედის და NULL-ს აბრუნებს.
![image](https://user-images.githubusercontent.com/62849715/99511458-b6e70900-29a1-11eb-8968-568e3d48c917.png)

**Comment by Gnems19** [comment]
ჩემთანაც ეგრე აგდებს

**Comment by d-chechelashvili** [comment]
რაღაც ფაილებზე არ მუშაობს გადმოცემული კოდი და დაანებეთ მაგათ თავი, არ მოგეთხოვებათ მაგათი გასწორება
