### ISSUE TITLE
ჩამოტვირთვის მერე make ბრაძანებაზე error აქვს

### ISSUE THREAD

**Issue by DavitInjgia** [freeuni-paradigms/assn-4-rss-news-search#14]
![error](https://user-images.githubusercontent.com/69914940/99514962-c8321480-29a5-11eb-944f-b83b35969dcf.PNG)

**Comment by CSopiko** [comment]
იგივე პრობლემაა ჩემთანაც :/

**Comment by d-chechelashvili** [comment]
@DavitInjgia 
sudo apt-get install gcc-multilib

sudo apt-get install libc6-dev-i386

sudo apt-get install libc6-dbg:i386

ამ სამიდან რომელიმემ უნდა უშველოს წესით, ზუსტად რომელი სჭირდება არ ვიცი. გაუშვი სამივე, დაარესტარტე კომპიუტერი და იმუშავებს თუ არ იმუშავებს დაწერე აქ.

**Comment by DavitInjgia** [comment]
davayene samive magram mainc ar mushaobs

**Comment by d-chechelashvili** [comment]
დაარესტარტე?

**Comment by DavitInjgia** [comment]
ki ubuntu davarestarte da exla curl ze aris error

**Comment by CSopiko** [comment]
მანდ უკვე curl-ის დაყენება უნდა 
sudo apt get-install curl მგონი

**Comment by d-chechelashvili** [comment]
@DavitInjgia 32 ბიტიანი ვერსია დაგჭირდება, sudo apt-get install libcurl4-gnutls-dev:i386 ესაა ბრძანება წესით.

**Comment by DavitInjgia** [comment]
gasworda, madloba
