### ISSUE TITLE
libcurlis problema

### ISSUE THREAD

**Issue by lukamacho** [freeuni-paradigms/assn-4-rss-news-search#2]
gcc -g  -m32 -Wall -std=gnu99 -Wno-unused-function    -c -o rss-news-search.o rss-news-search.c
rss-news-search.c:7:10: fatal error: curl/curl.h: No such file or directory
    7 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: rss-news-search.o] Error 1

amas miwers libcurli bevrjer gadmovwere sxvadasxvanairad magram ar ushvela

**Comment by gkhelo** [comment]
ჩემთანაც იყო მსგავსი პრობლემა და ამან უშველა:
sudo ln -s /usr/include/x86_64-linux-gnu/curl /usr/include/curl

თუ არ გამოვიდა, ესეც ცადე მერე:
sudo dpkg --add-architecture i386
sudo apt-get install libcurl4:i386

**Comment by lukamacho** [comment]
gcc rss-news-search.o -g  -m32 -Wall -std=gnu99 -Wno-unused-function -g  -lnsl -lrssnews -lcurl -Llinux -o rss-news-search
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libcurl.so when searching for -lcurl
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libcurl.a when searching for -lcurl
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: rss-news-search] Error 1

axla imas agar migdebs mara es gamoagdo

**Comment by gkhelo** [comment]
curl-ის 32ბიტიანი ვერსია გჭირდება.
ესენი ცადე:
sudo dpkg --add-architecture i386
sudo apt-get install libcurl4:i386
sudo apt-get install libcurl4-gnutls-dev:i386

**Comment by lukamacho** [comment]
gasworda madloba
