### ISSUE TITLE
პროგრამის output-ის შემოწმება

### ISSUE THREAD

**Issue by ltsil19** [freeuni-paradigms/assn-4-rss-news-search#3]
ტესტ ფაილზე შემდეგ შედეგს ვიღებ:
Please enter a single query term that might be in our set of indices [enter to quit]: batumi

	1.) "data/test1.txt" [search term occurs 6 times]
	    "data/test1.txt"
	2.) "data/test3.txt" [search term occurs 2 times]
	    "data/test3.txt"
	3.) "data/test2.txt" [search term occurs 1 time]
	    "data/test2.txt"

assn-4-checker-64 ის ტესტებზე კი არ გადის და მაინტერესებს output-ის ფორმატშია შეცდომა თუ სხვაგან.

**Comment by gkhelo** [comment]
ტესტები სწორად მუშაობს. სავარაუდოდ output-ში გაქვს შეცდომა. აქ რაც წერია სწორია. მხოლოდ ის არ ჩანს თითოეული ხაზის ბოლოს \n ეგრევე გიწერია თუ მაგალითად ჯერ ერთი სფეისი და მერე \n. ეგ ნახე აბა, ხაზის ბოლოს პირდაპირ \n უნდა გეწეროს. და კიდევ რიცხვების ქვევით ხაზებზე ოთხი სფეისი უნდა იყოს და მერე სახელი, ეგ მგონი სწორად გაქვს, მაგრამ ნახე მაინც.

**Comment by ltsil19** [comment]
მგონი ეგრე მაქვს. 
ესე მთავრდება პირველი ხაზი - printf("[search term occurs %d times]\n", c->numApps); (ან time, როცა numApps 1-ია)
და ეს მეორე -  printf("    \"%s\"\n", c->a.articleUrl);

რატომღაც ერთი სფეისი დაწერა აქ მეორე ხაზზე, მაგრამ ოთხი მიწერია

**Comment by gkhelo** [comment]
printf("%d.) \"%s\" [search term occurs %d times]\n", რიგის_ნომერი, სათაური, c->numApps);
printf("    \"%s\"\n", c->articleUrl);

აბა ასე სცადე

**Comment by gkhelo** [comment]
გიტჰაბი რაღაც უცნაურად წერს. დავსქრინავ რას ვგულისხმობ
![Screenshot from 2020-11-10 15-19-44](https://user-images.githubusercontent.com/62372651/98667741-453b0980-2368-11eb-8f31-121a66bb3c73.png)

**Comment by ltsil19** [comment]
![image](https://user-images.githubusercontent.com/73903576/98668276-196c5380-2369-11eb-8b5d-574a4e37029d.png)

ტესტებზე არ გადის მაინც. იქ ოთხი სფეისია.

**Comment by ggvar19** [comment]
არც ჩემი გადის... შეცდომა ვერ ვიპოვე გამოტანაში, ხელითაც შევამოწმე მონაცემები

**Comment by d-chechelashvili** [comment]
./assn-4-checker-64 ./rss-news-search -v ეს ბრძანება გაუშვით და expected output როგორაა წარმოდგენილი ნახავთ, დაგეხმარებათ გასწორებაში

**Comment by ggvar19** [comment]
![Screenshot from 2020-11-14 05-04-54](https://user-images.githubusercontent.com/72475246/99147666-a2b8aa00-2637-11eb-8fe9-086a640db1d1.png)

Ase gamoaq da arasworia mainc?

**Comment by d-chechelashvili** [comment]
"Readed Result From Program output" - ის მერე უნდა ბეჭდავდეს შენმა პროგრამამ რაც გამოიტანა, შენი ბეჭდავს \n-ს( ჩემთან წავშალე ყველა პრინტი და ცარიელი ხაზი არ იყო "Expected:"-მდე). კოდს გადახედე კარგად დაფიქრდი რატომ შეიძლება ხდებოდეს ეგრე. ჩემი აზრით, შენი კოდიდან უნდა იყოს გასასწორებელი, მეორე დავალებაზე იყო მსგავსი პრობლემა და აღმოჩნდა, რომ კოდში სხვა ადგილას აბეჭდინებდა და სხვაგან უნდა დაებეჭდინებინა - https://github.com/freeuni-paradigms/assn-2-six-degrees/issues/4.

**Comment by ggvar19** [comment]
Yvela printf() davakomentare magram mainc gamotovebuli xazia "Readed Result From Program Output"-is shemdeg. 
WorldIsWellFormed() funqciashi chavamate pirvel xazshi printf("TEST\n") da mxolod ramdenime testshi gamoitana "Readed Result.."-is mere

**Comment by d-chechelashvili** [comment]
დავალების თავიდან გადმოწერა და კოდის ახალ ფაილებში ჩაკოპირება სცადე? თუ მაგანაც არ უშველა დაწერე და ვეცდები კიდე მოვიფიქრო რამე :დ

**Comment by ggvar19** [comment]
Ki axla vcade zustad. QueryIndices()-mde rac ki printf iyo yvelaferi davakopire, davtove marto "Please enter a single term" da ProccessResponse() funqciashi rac ewera isini mxolod. Chemi kodi vafshe ar damiweria da mainc \n miwers. Ubralod imaze meshleba nervebi swori informacia ro gamoaq "arasworad" :D

Bodishi shewuxebistvis

**Comment by ggvar19** [comment]
WordIsWellFormed() - es funqcia aris organ, ScanArticle() da ProcessResponse() funqciebshi.
Pirvel screen-shi aris ./assn-4-checker-64 ./rss-news-search -v commandi gashvebuli roca printf("TEST\n") ar mqonda dawerili.
Danarchen screenebshi ubralod gamotanil result-s vscrollav. rasac davakvirdi, es gaaketa mxolod "Batumi"-s datestvisas. 

![Screenshot from 2020-11-17 00-28-56](https://user-images.githubusercontent.com/72475246/99365664-746fe000-286c-11eb-93cf-cbfe57181545.png)
![Screenshot from 2020-11-17 00-29-20](https://user-images.githubusercontent.com/72475246/99365669-76d23a00-286c-11eb-95d2-3a8a1031838f.png)
![Screenshot from 2020-11-17 00-29-38](https://user-images.githubusercontent.com/72475246/99365675-789bfd80-286c-11eb-80f3-eb5272b84b1f.png)
![Screenshot from 2020-11-17 00-29-44](https://user-images.githubusercontent.com/72475246/99365681-7a65c100-286c-11eb-81ce-8d4f928112fc.png)
