### ISSUE TITLE
cannot find libraries

### ISSUE THREAD

**Issue by ggvar19** [freeuni-paradigms/assn-4-rss-news-search#4]
/usr/bin/ld: cannot find -lnsl
/usr/bin/ld: cannot find -lcurl

ამას მიწერს make-ს რომ ვუშვებ და რითი ვუშველო?

**Comment by iarigby** [comment]
მითითებული პროგრამები დააყენე?

**Comment by ggvar19** [comment]
valgrind და zip დაყენებული მაქვს. ფედორას დისტრიბუცია მაქვს დაყენებული და libcurl-gnutls ვერ ეძებდა, და ასეთი კომანდი გავუშვი: sudo dnf install libcurl-*, მერე cannot find -lnsl რო მიგდებდა დავაყენე sudo dnf install libnsl და მაინც არ შვრებოდა არაფერს

**Comment by iarigby** [comment]
ამ კვირას გადამევსო ინბოქსი და ვეღარ გიპასუხე, 32 ბიტიანი ვერსიები გჭირდება
სავარაუდოდ და იმედია გითხრა სხვამ.

**Comment by ggvar19** [comment]
არ უთქვამს არავის, 32 ბიტიანი ვერსიებიც მქონდა დაყენებული და არაფერი უშველა. დავაყენე უბუნტუ. ახლა საერთოდ სხვა პრობლემა შემექნმა, მონაცემები სწორად გამოაქ მარა ტესტერი მაინც FAILED წერს...

**Comment by iarigby** [comment]
@freeuni-paradigms/section-leaders

**Comment by d-chechelashvili** [comment]
რა აზრიც გამოვიტანე თავდაპირველი პრობლემა მოიხსნა, ხოლო ახალი პრობლემის issue არის უკვე. თუ ასეა close issue ქენი როცა ნახავ. თუ არაა ასე ეგეც დაწერე :დ @ggvar19
