### ISSUE TITLE
ScanArticle() ფუნქციას არტიკლის სათაურის ნაცვლად ყოველთვის ცარიელი სტრინგი გადაეცემა

### ISSUE THREAD

**Issue by zurabmu** [freeuni-paradigms/assn-4-rss-news-search#7]
დავალების პირობაში წერია, რომ ორი არტიკლი ერთნაირია თუ მათი URL-ები ემთხვევა, **ან** სათაური ემთხვევათ და ერთი და იმავე სერვერიდანაა, შესაბამისად არტიკლის ინდექსირების დროს სათაური გვჭირდება, მაგრამ მხოლოდ საწყისი კოდს რომ ვუშვებ და გადმოცემულ articleTitle-ს ვაბეჭდინებ, ყოველთვის ცარიელ სტრინგს მიჩვენებს. ეს ჩვენი შესასწორებელია თუ საწყის კოდშია ხარვეზი?

**Comment by d-chechelashvili** [comment]
არაა თქვენი შესასწორებელი, საწყის კოდშია ხარვეზი პარსინგისას, მიწერილი მაქვს ლექტორისთვის დეტალები რა და როგორაა და ვნახოთ რას იტყვის. ასევე, დემოზე რომ მკითხე ვერ გავასწორე სამწუხაროდ.

**Comment by glekveishvili** [comment]
გავასწორე ეს პრობლემა, დასინქეთ აბა თქვენი კოდები გიტთან და ცადეთ თავიდან.

**Comment by zurabmu** [comment]
კი, ახლა მუშაობს.

**Comment by zurabmu** [comment]
პატარა ხარვეზია მაინც, RemoveCData() მეთოდის ბოლოს malloc()-ით გამოყოფილი მეხსიერების გათავისუფლებაა საჭირო. return-ის წინ free(contents); უნდა ეწეროს.

**Comment by glekveishvili** [comment]
დავამატე
