### ISSUE TITLE
ტესტერი output-ს ვერ ამოწმებს სწორად

### ISSUE THREAD

**Issue by zurabmu** [freeuni-paradigms/assn-4-rss-news-search#8]
მარცხნივ ტესტერის expected output არის, მარჯვნივ კი ჩემი პროგრამის output (ზედმეტი პრინტები მოვაშორე). მემგონი ორივე ერთნაირია და უბრალოდ ტესტერს აქვს ხარვეზი, თანაც სხვებმაც დაწერეს რომ ვერ ატარებენ ტესტებზე. შეგიძლიათ შეამოწმოთ რომ ტესტერი სწორად მუშაობს?
![Screenshot_6](https://user-images.githubusercontent.com/66688335/99255848-f55bb700-282d-11eb-8f32-055abab5b527.png)

**Comment by glekveishvili** [comment]
https://github.com/freeuni-paradigms/assn-4-rss-news-search/issues/3
