### ISSUE TITLE
ტესტირების კომანდები

### ISSUE THREAD

**Issue by lgela18** [freeuni-paradigms/assn-4-rss-news-search#9]
README -ში შეცდომით წერია მემორის ტესტების კომანდები:
./assn-4-checker ./rss-news-search -m

თუმცა შემდეგი ვარიანტებიც შეცდომას აბრუნებენ:
./assn-4-checker-32 ./rss-news-search -m
./assn-4-checker-64 ./rss-news-search -m
./assn-4-checker-32 ./rss-news-search -v -m
./assn-4-checker-64 ./rss-news-search -v -m

მე ამით შევამოწმე:
valgrind ./assn-4-checker-64 ./rss-news-search
და ყველაზე სწორად გადის( მემორიზეც და ჩვეულენრივ ტესტებზეც: ./assn-4-checker-64 ./rss-news-search)

ამიტიმ მაინტერესებს, რამე მაქვს შესაცვლელი თუ შეფასების დაწერისას ეს პრობლემას არ შექმნის.

**Comment by giorgi43** [comment]
**valgrind [valgrind-options] [your-program] [your-program-options].** მგონი რომ მაგ ბრძანებით valgrind მემორი ლიკზე assn-4-checker-64-ს ამოწმებს და არა თვითონ rss-news-search-ს

**Comment by lgela18** [comment]
malloc/free ების რაოდენობის მიხედვით წესით rss-news-search.c ს ამოწმებს, 
p.s. optionebi "-" ით უნდა იწყებოდეს

**Comment by giorgi43** [comment]
valgrind source ფაილში არ იხედება და არ ამოწმებს malloc/free ების რაოდენობის მიხედვით memory leaks, თუ ეს იგულისხმე.
მაგ ბრძანებით valgrind assn-4-checker-64-ს გაუშვებს და დაიწყებს შემოწმებას. assn-4-checker-64 თავის მხრივ rss-news-search-ს უშვებს დასატესტად, სავარაუდოდ ცალკე პროცესში. და როგორც გავიგე დეფაულტად child პროცესებს არ ამოწმებს ვალგრინდი. ძალით შექმენი მემორი ლიკი და გაუშვი აბა იგივე ბრძანება რას დაგიწერს.
პ.ს '-' არ უწერია მარა ტექნიკურად option ად ითვლება მაინც ამ შემთხვევაში:დ

**Comment by d-chechelashvili** [comment]
ქლასრუმზე დავწერე, აქაც დავწერ : ვინც ./assn-4-checker-64 ./rss-news-search -m ბრძანებას ვერ უშვებთ უნდა დააყენოთ libc6-dbg:i386, sudo apt-get install libc6-dbg:i386 ამ ბრძანებით. 

ვისაც არ მოგწონთ რომ უბრალოდ memory check failed წერს და მეტი ინფორმაცია გინდათ, შეგიძლიათ ხელით გაიმეოროთ იგივე პროცესი: გაუშვით valgrind ./rss-news-search და ის სამი სიტყვა შეიყვანეთ ხელით(mozzarella, Batumi, Festival) (kDefaultFeedsFile = "data/test.txt" უნდა გეწეროთ ამისთვის კოდში). ამის მერე უბრალოდ ენტერს დააწექით რომ მორჩეს პროგრამა და ვალგრინდი დაწერს ზუსტად თავის აუთფუთს.

 valgrind ./assn-4-checker-64 ./rss-news-search გაშვებით არასწორ შედეგს მიიღებ, მხოლოდ გარე პროგრამას ტესტავს ეგ წესით. ვცადე ჩემ კოდში, ყველა free დავაკომენტარე და მაინც success-ს მიწერდა ეგრე გაშვებისას

**Comment by lgela18** [comment]
<33
